### PR TITLE
Upstream changes neoway

### PR DESCRIPTION
**Pull request by gabo1208**
Multiple changes used on https://github.com/knative-sandbox/eventing-rabbitmq/issues/366

### CODE REVIEW

**Comment by i4ki** [comment]
Hi @gabo1208 ,

All the changes are reasonable except this one: https://github.com/NeowayLabs/wabbit/pull/52/files#diff-2c915c5f24aae4311567d2a13560c9bb152a0ca901b65a931f080fadd263a83fR89

If you can remove the "headers" implementation or implement it, then it's ok to merge.

Thanks for the contributions.

**Comment by gabo1208** [comment]
> Hi @gabo1208 ,
> 
> All the changes are reasonable except this one: https://github.com/NeowayLabs/wabbit/pull/52/files#diff-2c915c5f24aae4311567d2a13560c9bb152a0ca901b65a931f080fadd263a83fR89
> 
> If you can remove the "headers" implementation or implement it, then it's ok to merge.
> 
> Thanks for the contributions.

Let me try to fix that headders implementation if that is ok :)! But thans for the quick reply @i4ki

**Comment by gabo1208** [comment]
Hey @i4ki the headers exchamge interface is ready, if you can take a look :)

**Comment by i4ki** [comment]
Hi @gabo1208 

looks good!

Thanks.

**Comment by i4ki** [comment]
@matheusvill @lborguetti 

can you guys merge?

**Pull request merged**
