### PR TITLE
Implement rudimentary support for publisher confirmations.

### PR DESCRIPTION
**Pull request by nnathan**
This is very rudimentary support for publish confirmations and currently only supports the `NotifyPublish`.

~~Let me know if you would like a unit test in amqptest.go. I could incorporate it into the exiting TestPubSub or create a new test scenario.~~ I incorporated publisher confirms in the TestPubSub.

### CODE REVIEW

**Comment by nnathan** [comment]
I'm not sure why the code coverage doesn't pick up on the tests I've used.

**Comment by tiago4orion** [comment]
Sorry for the late review!

Nice work. But we aren't using rabbitmq anymore, and then this makes far more hard to ensure the project continue to work as expected.

I'm merging the PR now, but what do you think in contribute directly on this repo? If you like the idea, I'll give commit rights to you.

**Comment by nnathan** [comment]
Sure that would be good. I'm planning to include any missing (useful) features as they arise, plus I have a better feel for the overall layout of the passthrough and test server code.

**Comment by tiago4orion** [comment]
=)

Done.

I really appreciate your contributions!
Thanks!

**Pull request merged**
