### PR TITLE
Add amqp.Delivery.MessageId support

### PR DESCRIPTION
**Pull request by keinohguchi**

### CODE REVIEW

**Comment by tiago4orion** [comment]
Thanks @keinohguchi =)

**Comment by keinohguchi** [comment]
thanks @tiago4orion!

**Comment by keinohguchi** [comment]
@tiago4orion, what is your take on this test blocking in the master?

https://travis-ci.org/NeowayLabs/wabbit/builds/352078041?utm_source=github_status&utm_medium=notification

I've tried `hack/check.sh` against the master and see the `TestDial` blocking.  I believe this is not related to the `MessageId` change, as it doesn't affect the Dial sequence, but who knows.

I'll explore the reason why but just want to sync up with you here, just in case you're investigating the issue.

**Comment by tiago4orion** [comment]
hmm I don't have time to investigate this now, but it's probably related to the way wabbit starts rabbitmq with docker for testing Dial. I just saw that we don't use a fixed rabbitmq docker image, maybe something changed on the latest tag... But it's just a guess, sorry =/

EDIT: I have restarted the build and now the error is:

```
--- FAIL: TestDial (337.77s)
	dial_test.go:121: no matching manifest for linux/amd64 in the manifest list entries
panic: isn't possible to connect on rabbitmq [recovered]
	panic: isn't possible to connect on rabbitmq
```
Maybe something related to docker indeed.

**Comment by keinohguchi** [comment]
Thanks @tiago4orion for your quick double checking!  Really appreciated!  I'll keep an close eyes to it.

**Pull request merged**
