### PR TITLE
Add support to worker queue

### LINKED ISSUE #5: Testing without Routing
Hey ! 

I'm trying to test  [work queues approch](https://www.rabbitmq.com/tutorials/tutorial-two-go.html).

Follow the code:

```Go
fakeServer := server.NewServer("amqp://guest:guest@localhost:5672")
fakeServer.Start()
defer fakeServer.Stop()

mockConn, err := amqptest.Dial("amqp://guest:guest@localhost:5672") // now it works =D

if err != nil {
  t.Error(err)
}

ch, err := mockConn.Channel()

if err != nil {
  t.Error(err)
}

q, err := ch.QueueDeclare("data-queue", nil)

if err != nil {
  t.Error(err)
  return
}

deliveries, err := ch.Consume(
  q.Name(),
  "",
  nil,
)

if err != nil {
  t.Error(err)
  return
}

err = ch.Publish("", "process.data", []byte("teste"), nil)

if err != nil {
  t.Error(err)
  return
}

data := <-deliveries

if string(data.Body()) != "teste" {
  t.Errorf("Failed to publish message to specified route")
  return
}
```

After one run it, I've got the error: `No bindings to route: process.data`

So, How Should I testing Work Queues (without exchange, bind...) using your package ?

### PR DESCRIPTION
**Pull request by lucasgomide**
Closes #5

### CODE REVIEW

**Comment by lucasgomide** [comment]
I've created a issue #7   to talking about that [build](https://travis-ci.org/NeowayLabs/wabbit/jobs/210049300) on travis

**Comment by tiago4orion** [comment]
The PR is ok, but by AMQP-0-9-1 spec, the work queues mode is a special case of exchange mode. Take a look in the section 2.1.2.4 of [spec](https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf). The link below has a more detailed explanation: 
https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-default

As you can see, the implementation for this is much more easy =)
We only need to add a implicit (automatic) binding in [default exchange](https://github.com/NeowayLabs/wabbit/blob/master/amqptest/server/vhost.go#L34) (the empty one) to every queue declared. And then work queues will work through a default exchange binding. 

`QueueDeclare` should be something like:

```go
func (v *VHost) QueueDeclare(name string, args wabbit.Option) (wabbit.Queue, error) {
	if q, ok := v.queues[name]; ok {
		return q, nil
	}

	q := NewQueue(name)

	v.queues[name] = q
	err := v.QueueBind(name, name, "", nil)

	if err != nil {
		return nil, err
	}

	return q, nil
}
```

I think `DirectExchange` don't have tests, then maybe will need something more else to make it happen. 

What do you think? Can you test if this works?

Thanks!

**Comment by lucasgomide** [comment]
@tiago4orion Can you review again? 

I'll make some tests to DirectExchange, as soon as possible.

**Comment by lucasgomide** [comment]
Hey @tiago4orion !
I've created a new test on QueueDeclare, to check if the queue has been binding.

Can you tell me why did u ask me to make some tests for `DirectExchange` ? I did not changes nothing about `DirectExchange`

**Comment by lucasgomide** [comment]
@tiago4orion I'll squash those commits, before u merge it. ok ?

**Comment by tiago4orion** [comment]
> Can you tell me why did u ask me to make some tests for DirectExchange ? I did not changes nothing about DirectExchange

I haven't said to you add more testing but for test if the solution I'd proposed would work.

> @tiago4orion I'll squash those commits, before u merge it. ok ?

no problem.

**Comment by lucasgomide** [comment]
> I haven't said to you add more testing but for test if the solution I'd proposed would work.

Okay. I did it. 

So.. It's everything ok to merge it ? 
Do you have others points  ?

**Comment by tiago4orion** [comment]
LGTM

**Comment by lucasgomide** [comment]
noice 
🚶🏻💃🏼

**Pull request merged**
